### ISSUE TITLE
issues and roadmap

### ISSUE THREAD

**Issue by alexisargyris** [svsool/vscode-memo#1]
Hi!

Could you please provide some additional info regarding Memo, specifically if there are any known issues, any feature roadmap that you may have in mind, how it compares/differs to/from similar efforts (e.g. foam)?

Thanks a lot!

**Comment by svsool** [comment]
Hello @alexisargyris, and thanks for asking!

About known issues and VSCode limitations which I encountered during the development:

- One can't drag an image onto text editor to get a link out of it, so I have to figure out how to make pasting images more convenient
   - One can still drag and drop an image onto file tree, and use links autocomplete or use Markdown paste plugin to paste an image from clipboard
- [Image preview on hover](https://github.com/svsool/vscode-memo/blob/8184e682474e3401f9bb94711c6b18c7ba250c52/src/extensions/ReferenceHoverProvider.ts#L38) for images with UNC paths does not work with Windows due to VSCode CORS settings, but local paths work just fine 
- I can imagine that Memo will not perform well on the knowledge base with thousands of files, because it does not use indexing yet and calculates references on the fly using some thin cache layer. Still, it works fine with my knowledge base which is around ~2000 small notes
- Links that are not created to filesystem won't appear in the autocomplete results (something that I realized recently). Memo scans all notes and images in the opened workspace, but does not consider links that are not created to filesystem

Roadmap / thoughts:

- Better search. Built-in VSCode search is not nearly as good as it could be for knowledge base
  - for instance, boolean logic can be used to make queries imagine searching by multiple links
  - excluding certain references from results while searching
  - fuzziness
  - amount of words around link
  - etc.
- Memo friendly pasting of images from clipboard, so far I use Markdown paste plugin for that which also adds Markdown image in this format `![alt](src)` to the text editor, ideally it should be a Memo resource link instead
- Markdown paste feature will be awesome, when one copies website content and html from clipboard automatically converted to markdown on pasting it to the text editor, I so far use this https://euangoddard.github.io/clipboard2markdown/ (Markdown paste does not work for me for some reason - it does not convert html to markdown on executing paste command in VSCode)
- Graph panel - I did not find it very useful for myself, but most of knowledge bases usually have it, so it can be introduced on collecting more upvotes or if someone would find time to contribute
- Finding dangling links and links that are not created yet to the filesystem
- Todo panel - show all incompleted todos
- Daily notes panel - show all daily notes in all folders across knowledge base (workspace)

About comparison with similar tools, such as Foam. I did not try Foam, so I can't easily compare Memo and Foam. I tried Obsidian and RoamResearch. RoamResearch has a different concept to Memo and uses Datomic and blocks under the hood. I'd call Roam the most advanced tool in this category that I ever tried. I enjoyed using everything-is-a-link functionality in Roam and advanced filters, offline sync is nice too! The biggest downside for me with Roam was no end-to-end encryption for the whole workspace (only specific blocks supported), all data from Datomic ends up in Firebase in open format and everyone at Roam and Google can read your notes. Speaking of Obsidian, Memo is quite close to Obsidian, the main difference that Obsidian is built on top of CodeMirror and Memo is built on top VSCode, so one can expect more advanced editing features with VSCode. Other features that I can recall existing in Obsidian, but missing in Memo :

- Graph panel (maybe)
- Pasting images from clipboard (planning to add)
- Dragging image on text editor directly (VSCode limitation)
- Markdown importer from RoamResearch and Zettelkasten (maybe)
- Audio recorder (maybe)
- Starred notes (maybe)

I'm looking forward to contributions and more ideas.

Thank you!

**Comment by alexisargyris** [comment]
That was really useful, many thanks. I'll start using Memo and suggest/vote for features.
