### ISSUE TITLE
Create daily note with default title

### ISSUE THREAD

**Issue by srid** [svsool/vscode-memo#107]
Create the *new* daily note with a default title (matching filename):

```markdown
# 2020-09-12

```

I find myself doing this manually anyways; would be nice if the extension did it automatically. Users who don't need it can always `Ctrl+A DEL` it.

Why do I need it? Because the [markdown-links](https://github.com/tchayen/markdown-links) extension requires a level-1 heading.

**Comment by svsool** [comment]
Thanks for the idea. I think it should not be included in the core because it would limit other users. For instance, I don't need it for my daily notes and consider it redundant since the title already contains it. 

You can achieve it via [Auto Snippet](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.auto-snippet) extension.

```
// settings.json
"autoSnippet.snippets": [
    {
      "pattern": "**/\\d{4}-\\d{2}-\\d{2}.md",
      "snippet": "daily"
    },
  ],
// markdown.json with snippets
{
  "daily": {
    "prefix": "daily",
    "body": "# ${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}",
  }
}
```

![Daily Note Auto Snippet](https://user-images.githubusercontent.com/1452141/93000387-e5271300-f530-11ea-8921-78c8ea9171f6.gif)

**Comment by srid** [comment]
Related question: is it possible to change the *location* of the daily note? For eg., `/Calendar/2021/05/2021-05-18.md`.
