### ISSUE TITLE
How to exclude node_modues directory

### ISSUE THREAD

**Issue by carvinlo** [svsool/vscode-memo#116]
How to exclude node_modues directory ?

**Comment by svsool** [comment]
Please expand what is the current problem and what you want to achieve.

**Comment by svsool** [comment]
I checked Memo's autocomplete and search settings are not inherited with `findFiles`, so it needs some improvements. I guess your question was related to it. I'll take a look at it when I have time.

**Comment by carvinlo** [comment]
Yeah, you are right, except that it cannot be automatically reminded and cannot be deleted. I am editing this project with memo plugin [piral](https://github.com/smapiot/piral/tree/develop/docs). memo plugin is very good! Thanks!

**Comment by svsool** [comment]
Since [v0.2.0](https://github.com/svsool/vscode-memo/releases/tag/v0.2.0) `search.exclude` and `file.exclude` settings should be taken into account in autocomplete results. Remember to update Memo extension via marketplace.

![image](https://user-images.githubusercontent.com/1452141/93713011-f049f680-fb61-11ea-8d45-db5a139ea586.png)

![image](https://user-images.githubusercontent.com/1452141/93712995-e627f800-fb61-11ea-9aaf-7660dcb16f3a.png)
