### ISSUE TITLE
Backlinks are broken if there is a dot in filename

### ISSUE THREAD

**Issue by srid** [svsool/vscode-memo#120]
To reproduce,

1. Rename any zettel note that has non-zero backlinks
   1. Rename to a filename that has dot in it (eg: `Some foo.bar.md`)
1. Go to the renamed zettel
1. The backlinks panel will now be empty

**Comment by svsool** [comment]
Hi, I'm unable to reproduce.

When you rename via "Rename Symbol" command and have a dot in the filename (or second extension) remember to add `.md` explicitly, otherwise, Memo will infer extension directly from the link, which is for instance useful in case of images and pdfs. Memo supports [various extensions](https://github.com/svsool/vscode-memo/blob/master/src/utils/utils.ts#L14-L44) besides `.md` in the links.

In the following screencast I tried both ways via file rename and via "Rename Symbol" command and in both cases Backlinks Panel worked as it should:

![issue #120](https://user-images.githubusercontent.com/1452141/93713297-8599ba80-fb63-11ea-8d4e-face5c0e77e5.gif)

**Comment by srid** [comment]
I renamed to a text like "Foo v1.0 release".

I'll try the .md trick, and create a screencast of the bug if it still
happens again.

**Comment by svsool** [comment]
Looks like Node's `path.parse` function considers `0 release` as an extension 😅:

```
❯ node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> path.parse('Foo v1.0 release')
{
  root: '',
  dir: '',
  base: 'Foo v1.0 release',
  ext: '.0 release',
  name: 'Foo v1'
}
```

But anyway, please ensure that `Foo v1.0 release` has `.md` in the filename after the rename.

**Comment by svsool** [comment]
Even though it works as designed, I realized that it could be improved either by adding `.md` in the rename popup explicitly or by checking the filename's current extension and adding it automatically since it might not be evident that the user should add it.

**Comment by svsool** [comment]
It should work as intended in [v0.2.1](https://github.com/svsool/vscode-memo/releases/tag/v0.2.1) (just released). Please remember to update Memo extension and reload VS Code.
