### ISSUE TITLE
Backlinks do not show with relative paths

### ISSUE THREAD

**Issue by mjshashank** [svsool/vscode-memo#209]
When I have files with conflicting names (in my case, one inside a subdirectory and one at the root level), the backlinks panel does not show up the linked note.

Is this a know issue?

**Comment by mjshashank** [comment]
For more context:

This is my structure:

--sample/
  --sample-1.md
  --sample-2.md
  --test.md
--test.md


There is wiki link in sample-1.md like `[[sample/test.md]]` and a wiki link in sample-2.md like [[test.md]].

For the backlinks panel of sample/test.md
1. It shows sample-2.md which is an incorrect backlink
2. It doesn't show sample-1.md which is a missing backlink

For the backlinks panel of test.md
1. It shows only sample-2.md which is the right backlink


Attaching screenshots below:

![Screenshot 2020-12-03 at 2 39 54 PM](https://user-images.githubusercontent.com/16825130/100988781-19c9ca00-3576-11eb-8d2e-5e5c316b634c.png)
![Screenshot 2020-12-03 at 2 40 20 PM](https://user-images.githubusercontent.com/16825130/100988843-2bab6d00-3576-11eb-8d04-ae5b079678f0.png)
![Screenshot 2020-12-03 at 2 40 15 PM](https://user-images.githubusercontent.com/16825130/100988828-277f4f80-3576-11eb-8d6e-0974d605b584.png)
![Screenshot 2020-12-03 at 2 40 24 PM](https://user-images.githubusercontent.com/16825130/100988848-2cdc9a00-3576-11eb-8e7d-4c0a09e6a633.png)

**Comment by svsool** [comment]
Thanks for reporting. It was fixed in will be released in the next version.

**Comment by Hocnonsense** [comment]
I also meet this question. I think it is necessary to treat absolute path and relative path in different manner.

**Comment by svsool** [comment]
Links format is configurable via settings, @Hocnonsense.

![image](https://user-images.githubusercontent.com/1452141/103468401-6bc26300-4d61-11eb-809b-769f3b1f8caa.png)

**Comment by Hocnonsense** [comment]
Thanks for your advice. And this may be a feature request. Should I open a new issue?

What I mean is that it should recognize `/` `./` and `../`.

For example, when I'm reading journals, my note look like this:
```
/+ root
 |
 +--/+ doi1
 |   |
 |   +--+ Introduction.md
 |   |
 |   +--+ Methods.md
 |   |
 |   +--+ Results.md
 |   |
 |   +--+ README.md
 |
 +--/+ doi2
 |   |
 |   +--+ Introduction.md
 |   |
 |   +--+ Methods.md
 |   |
 |   +--+ Results.md
 |   |
 |   +--+ README.md
 |
 +-- README.md
```
So when i wrote `[[README]]` in `/doi1/Introduction.md`, I hope it could refer to `/doi1/README.md`, or allow me to write `[[./README]]`. (Now I have to write `[[doi1/README]]`, however it don't suit vscode manner because there don't exist a `/doi1/doi1/README.md`)

It is necessary when you maintain a large library containing knowledge from several domain, when several abbreviations are the same, and when you want to reconstruct or split the large library.

After all, I'me grateful for your excellent `vscode-memo`. It helped me a lot!!
