### ISSUE TITLE
Support jump by line number 

### ISSUE THREAD

**Issue by Aphrodit** [svsool/vscode-memo#280]
Use line number to jump into the text, example:
`[[example:32]]`
Click the link, can jump to the 32 line in example.md

**Comment by svsool** [comment]
Hi,

I think it won't be a very useful feature because lines are prone to changes which could result in stale link. Probably a better solution would be to have some level of transclusion when blocks from other notes can be referenced instead, but it would require a more significant effort to implement.

Something like [this](https://publish.obsidian.md/help/How+to/Link+to+blocks).
