### ISSUE TITLE
Include '.md' in links

### ISSUE THREAD

**Issue by gohma231** [svsool/vscode-memo#299]
I'm wondering if there is support for including the '.md' extension when linking to markdown files.

**Comment by svsool** [comment]
Until I had no reason to support it 🙂 . I have to admit that `.md` on its own is quite useless information in my knowledge base.

Since links can be created ad-hoc just by typing a [[word]] and clicking on it, for the sake of avoiding ambiguous cases all links without extension automatically point to an `.md` file until extension explicitly specified like `[[image.png]]`. Another benefit also is that user types less. All linkable extensions besides `.md` specified in [this file](https://github.com/svsool/vscode-memo/blob/master/src/utils/utils.ts). 

I also do use some links as tags [[work]], [[learning]] etc. they are not created to the disk but used for searching through past notes and references and `.md` doesn't make much reason too in my case because they.
