### ISSUE TITLE
Zettlr like ID support

### ISSUE THREAD

**Issue by borisovandrey** [svsool/vscode-memo#41]
Is it possible to support zettlr-like ID's.

ID is represented as regex expression in setting.
Than the first string in the file considered to be id. Usually it is a data-time. But it has sense to add some prefix.
The link support shall also admit the ID's

So in some file we have a string:

ID:20200728172530

In another we have a link

[[20200728172530]] - this link shall work.

**Comment by svsool** [comment]
Hi,

I think it's possible, but hopefully, there is no need. 

Please try https://github.com/monferrand/mzettel. It should already support notes + filename templates. [The rest](https://github.com/svsool/vscode-memo/#features) Memo can provide. `mzettel` does not support ids within the content, but I think ids in filenames should be fine as well since Zettlkasten is not a standard, but a set of ideas and practices and unlikely there will be a solution that fits all cases.

Thanks, and feel free to reopen this issue if you have any questions.
