### ISSUE TITLE
Support for native markdown links []()

### ISSUE THREAD

**Issue by colerehbein** [svsool/vscode-memo#643]
I'm not sure if this has been addressed in design discussions or purposely not included in features, if so my apologies for opening the issue. Wikilinks are not native/"pure" markdown, thus they are not exactly portable between applications. Obsidian includes support for either [[]] or []() format for links. would it be possible to include the option to support native markdown links alongside wikilinks?

Thank you!

**Comment by svsool** [comment]
hi @colerehbein, a similar question was discussed [here](https://github.com/svsool/memo/issues/83#issuecomment-682866580), for now no support planned for native md links since memo is a wikilink based knowledge base.

consider exporting to a pure markdown using available export tools such as [this](https://github.com/zoni/obsidian-export) if you need normal markdown links.

thanks!
